name: 构建 AX6000-512M 纯净复活包

on:
  workflow_dispatch:
    inputs:
      profile:
        type: select
        description: "型号(大分区选 ubootmod)"
        required: true
        options:
          - xiaomi_redmi-router-ax6000-ubootmod
          - xiaomi_redmi-router-ax6000-stock
        default: xiaomi_redmi-router-ax6000-ubootmod
      custom_router_ip:
        description: "管理地址"
        required: true
        default: "10.0.0.2"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare Workspace
        run: |
          mkdir -p "${{ github.workspace }}/custom"
          echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"

      - name: Build 23.05 Stable (512M Mod)
        run: |
          profile="${{ github.event.inputs.profile }}"
          # 强制锁定最稳的 23.05.3 标签
          tag="mediatek-filogic-openwrt-23.05.3"
          
          cat << 'EOF' > patch_512m.sh
          echo "--- 应用大分区补丁 ---"
          find . -name "filogic.mk" | xargs sed -i 's/IMAGE_SIZE := .*/IMAGE_SIZE := 500000k/g'
          find . -name "*.dts*" | xargs sed -i 's/104448k/491520k/g'
          find . -name "*.dts*" | xargs sed -i 's/112640k/491520k/g'
          echo "--- 补丁应用成功 ---"
          EOF

          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/custom:/home/build/immortalwrt/files/etc/config" \
            -v "${{ github.workspace }}/mediatek-filogic/build24.sh:/home/build/immortalwrt/build.sh" \
            -v "${{ github.workspace }}/patch_512m.sh:/home/build/immortalwrt/patch_512m.sh" \
            -e PROFILE=$profile \
            -e INCLUDE_DOCKER='不' \
            immortalwrt/imagebuilder:$tag /bin/bash -c "bash /home/build/immortalwrt/patch_512m.sh && bash /home/build/immortalwrt/build.sh"

      - name: Upload Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: AX6000-23.05-PURE
          name: AX6000-23.05-大分区纯净版
          files: ${{ github.workspace }}/bin/targets/mediatek/filogic/*
          token: ${{ secrets.GITHUB_TOKEN }}
